name: Build
on:
    push:
        branches-ignore:
            - gh-pages
    workflow_dispatch:
    pull_request:
jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: '0'
                  persist-credentials: false
                  submodules: 'recursive'
            - name: Cache yarn
              uses: c-hive/gha-yarn-cache@v2
            - name: Install
              run: yarn install
            - name: Build
              run: yarn build
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.4
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
              with:
                  branch: gh-pages
                  folder: website
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: '0'
                  submodules: 'recursive'
            - name: Cache yarn
              uses: c-hive/gha-yarn-cache@v2
            - name: Install
              run: yarn install
            - name: Lint
              run: yarn lintci
